---
- name: MongoDB | Create directores for DB dumps
  file:
    path: '{{ item }}'
    state: directory
    group: adm
    mode: 0775
  with_items:
    - '/var/lib/backups'
    - '{{ mongodb_backup_path }}'

- name: MongoDB | Create DB dump script
  template:
    src: 'dump.sh.j2'
    dest: '{{ mongodb_backup_script }}'
    group: adm
    mode: 0750

- name: MongoDB | Configure DB dump timer
  include_role: name=systemd-timer
  vars:
    systemd_timer_name: dump-mongod
    systemd_timer_description: 'MongoDB dump job'
    systemd_timer_user: '{{ mongodb_backup_user }}'
    systemd_timer_frequency: '{{ mongodb_backup_frequency | default("daily") }}'
    systemd_timer_timeout_sec: '{{ mongodb_backup_timeout }}'
    systemd_timer_requires_extra: 'mongod.service'
    systemd_timer_script_path: '{{ mongodb_backup_script }}'
    systemd_timer_start_on_creation: false

- name: MongoDB | Configure S3 upload cron job
  include_role:
    name: s3cmd-backup
  vars:
    backup_name: mongod
    backup_number: 1
    backup_hour: 4
    backup_day: '*'
    backup_base_domain: 's3.amazonaws.com'
    backup_directory: '{{ mongodb_backup_path }}'
    backup_bucket_name: '{{ mongodb_backup_bucket_name | mandatory }}'
    backup_access_key: '{{ mongodb_backup_access_key | mandatory }}'
    backup_secret_key: '{{ mongodb_backup_secret_key | mandatory }}'
