---
- name: MongoDB | Create directores for backups
  file:
    path: '{{ item }}'
    state: directory
    group: adm
    mode: 0775
  with_items:
    - '/var/lib/backups'
    - '{{ mongo_backup_path }}'

- name: MongoDB | Create dump script
  copy:
    dest: '/var/lib/backups/mongodb_dump.sh'
    content: |
      #!/usr/bin/env bash
      TSTAMP=$(date -u +%Y%m%d%H%M%S)
      BKP_DIR={{ mongo_backup_path }}
      /usr/bin/docker exec \
        -i {{ mongo_cont_name }} mongodump \
        --verbose \
        --host=localhost \
        --port={{ mongo_cont_port }} \
        --db={{ mongo_db_name }} \
        --username={{ mongo_db_user }} \
        --password={{ mongo_db_pass }} \
        --authenticationDatabase=admin \
        --out=${BKP_DIR}/{{ mongo_cont_name | replace("-", "_") }}_dump_${TSTAMP}.bson
    group: adm
    mode: 0750

- name: MongoDB | Configure dump cron job
  cron:
    name: MongoDB Dump
    special_time: daily
    user: root
    job: '{{ mongo_backup_script }}'
