---
- name: Configure MongoDB
  hosts: db.dev
  roles:
    - mongodb-firewall
    - mongodb
  post_tasks:
    - name: MongoDB URI string
      debug:
        msg: 'mongodb://{{ mongodb_users[0].name }}:{{ mongodb_users[0].password }}@{{ dns_entry }}:{{ mongodb_net_port }}/{{ mongodb_users[0].database }}'
